name = "jittter-app"
main = "./server.ts"
compatibility_date = "2023-12-01"

keep_vars = false
[vars]
NEON_DATABASE_URL = "postgresql://christopherbilg:dv91LmpwCjVb@ep-weathered-sky-a5ilhn57-pooler.us-east-2.aws.neon.tech/jittter-product-db?sslmode=require"
TEST = "example"
